 
 CREATE DATABASE `ami_scanner`;
 
 CREATE TABLE `data` (
  `ami_id` char(50) NOT NULL,
  `aws_region` char(50) NOT NULL,
  `hostname` text,
  `users` text,
  `groups` text,
  `shadow` text,
  `history` text,
  `ssh_keys` text,
  `last_users` text,
  `motd` text,
  `services` text,
  `processes` text,
  `uname` text,
  `os` text,
  `crons` text,
  `aws_creds` text,
  `hosts` text,
  `env` text,
  `crontab` text,
  `authorized_keys` text,
  `sudoers` text,
  `sudoers_folder` text,
  `sts` text,
  `ami_create_date` datetime DEFAULT NULL,
  `create_result` text,
  `account_id` char(20) DEFAULT NULL,
  `redis` text,
  `redis_history` text,
  `mysql_showdb` text,
  `mysql_history` text,
  `jenkins` text,
  `fstab` text,
  `iptables` text,
  PRIMARY KEY (`ami_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4